services:
  - type: web
    name: automation-pm
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeployTrigger: checksPass
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

